### INSTALAÇÃO DE BIBLIOTECAS

In [ ]:
!pip install numpy
!pip install pandas
!pip install scikit-learn
!pip install matplotlib

### INTRODUÇÃO AO NUMPY

In [3]:
import numpy as np

In [5]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)

In [6]:
print(lista)
print(array)
print(type(lista))
print(type(array))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


In [11]:
## Arrays de zeros
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
print(array[0])

1


In [12]:
## Alterar valor de um array
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [14]:
## Matrizes
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
## Operações matemáticas

# Notas de alunos

lista_de_notas = [9.8, 5.6, 7.8, 9.3, 6.5]

notas = np.array(lista_de_notas)

print('Maximo', notas.max())
print('Minimo', notas.min())
print('Media', notas.mean())
print('Desvio Padrao', notas.std())
print('Posicao Menor', notas.argmin())
print('Posicao Maior', notas.argmax())




Maximo 9.8
Minimo 5.6
Media 7.8
Desvio Padrao 1.5987495113369077
Posicao Menor 1
Posicao Maior 0


### EXERCICIOS

In [26]:
## EX 1 - Você deseja criar um numpy array com 10 espaços, e depois preenchê-los com 10 valores para poder calcular o desvio padrão usando o método do numpy.
# Para fazer isso sem usar uma lista, você pode:
# A) Criar um array de zeros usando o comando np.zeros(10), e utilizar um for para preenchê-lo --> (CORRETA)
# B) Criar um array vazio usando o np.array() e depois fazer append dos dados
# C) Criar um array de "uns" usando o comando np.ones(10) e depois preencher o array igualando-o ele a uma lista
# D) Criar um array de zeros usando o comando np.zeros(9), pois a contagem começa no zero, e usar um for para preenchê-lo

arr = np.zeros(10)

# Preencher o array com 10 valores
for i in range(10):
    arr[i] = i + 1  # Exemplo: preenchendo com valores de 1 a 10

# Calcular o desvio padrão
std_dev = np.std(arr)
print(std_dev)




2.8722813232690143


In [27]:
## EX 2 - Juliana está corrigindo provas de seus alunos e para isso salva as notas em uma lista.
# Além de calcular a média da turma, Juliana também precisa determinar de forma rápida quem está acima e abaixo da média do colégio, e, para fazer isso de forma rápida, decidiu criar um array para auxiliá-la.
# A partir da lista de notas, como Juliana pode criar esse array?
# A) Utilizando o comando np.array(lista) --> (CORRETA)
# B) Utilizando a função np.to_array(lista)
# C) Utilizando a função Array(lista)
# D) Utilizando a função np.list_to_array(lista)

# Suponha que `notas` seja a lista de notas dos alunos
notas = [7.5, 8.0, 6.5, 9.0, 5.5, 8.5, 7.0, 6.0]

# Convertendo a lista em um array numpy
notas_array = np.array(notas)

# Calculando a média das notas
media_turma = np.mean(notas_array)
print("Média da turma:", media_turma)

# Determinando quem está acima e abaixo da média do colégio (por exemplo, média do colégio é 7.0)
media_colegio = 7.0
acima_da_media = notas_array[notas_array > media_colegio]
abaixo_da_media = notas_array[notas_array < media_colegio]

print("Notas acima da média do colégio:", acima_da_media)
print("Notas abaixo da média do colégio:", abaixo_da_media)



Média da turma: 7.25
Notas acima da média do colégio: [7.5 8.  9.  8.5]
Notas abaixo da média do colégio: [6.5 5.5 6. ]


### MASCARAS BOOLEANAS

In [33]:
is_covid_positive = np.array(['Yes', 'No', 'No', 'Yes', 'Yes', 'No'])

In [35]:
mask = (is_covid_positive == 'Yes')

In [36]:
print(is_covid_positive[mask])

['Yes' 'Yes' 'Yes']


In [37]:
is_covid_positive[mask] = 'C19'

In [38]:
print(is_covid_positive)

['C19' 'No' 'No' 'C19' 'C19' 'No']


In [39]:
notas = np.array([4.9, 6.5, 3.2, 6.7])

In [40]:
mask_notas = notas >= 5

In [41]:
print(mask_notas)

[False  True False  True]


### EXERCICIOS

In [ ]:
## EX 3 - Um estagiário está começando a trabalhar com Numpy. No meio dos tutoriais encontra menções a algo chamado máscara booleana.
# O conceito não ficou muito claro para ele, e ele pede a sua ajuda para explicar o que é esse recurso no numpy.
# Assinale a alternativa que explica o que é uma máscara booleana:

#a) É uma maneira de indexar objetos no numpy, que funciona de maneira similar a um dicionário
#b) É uma maneira de indexar objetos no numpy, que funciona de maneira similar a um filtro, que pode ser simples ou composto
#c) É uma maneira de indexar objetos no numpy, que funciona de maneira similar a um filtro, a filtragem deve ser simples
#d) É uma ferramenta do numpy para disfarçar variáveis False e fingir que são True, apenas por um periodo no código




In [ ]:
## EX 4 - Em uma escola, a média para aprovação é 7. As notas dos alunos estão armazenadas em um array chamado 'notas'.
#Escolha a expressão que pega 'notas' e salva em 'aprovados' um outro array booleano, com valor true apenas para as pessoas que passaram de ano:

#a) aprovados = notas >= 7
#b) aprovados = notas > 7
#c) aprovados <- notas >= 7
#d) aprovados = notas[notas >= 7]