### INSTALAÇÃO DE BIBLIOTECAS

In [ ]:
!pip install numpy
!pip install pandas
!pip install scikit-learn
!pip install matplotlib

### INTRODUÇÃO AO NUMPY

In [2]:
import numpy as np

In [5]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)

In [6]:
print(lista)
print(array)
print(type(lista))
print(type(array))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


In [11]:
## Arrays de zeros
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
print(array[0])

1


In [12]:
## Alterar valor de um array
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [14]:
## Matrizes
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
## Operações matemáticas

# Notas de alunos

lista_de_notas = [9.8, 5.6, 7.8, 9.3, 6.5]

notas = np.array(lista_de_notas)

print('Maximo', notas.max())
print('Minimo', notas.min())
print('Media', notas.mean())
print('Desvio Padrao', notas.std())
print('Posicao Menor', notas.argmin())
print('Posicao Maior', notas.argmax())



Maximo 9.8
Minimo 5.6
Media 7.8
Desvio Padrao 1.5987495113369077
Posicao Menor 1
Posicao Maior 0


### EXERCICIOS DE FIXAÇÃO I

In [11]:
## EX 1 - Você deseja criar um numpy array com 10 espaços, e depois preenchê-los com 10 valores para poder calcular o desvio padrão usando o método do numpy.
# Para fazer isso sem usar uma lista, você pode:
# A) Criar um array de zeros usando o comando np.zeros(10), e utilizar um for para preenchê-lo --> (CORRETA)
# B) Criar um array vazio usando o np.array() e depois fazer append dos dados
# C) Criar um array de "uns" usando o comando np.ones(10) e depois preencher o array igualando-o ele a uma lista
# D) Criar um array de zeros usando o comando np.zeros(9), pois a contagem começa no zero, e usar um for para preenchê-lo

arr = np.zeros(10)

# Preencher o array com 10 valores
for i in range(10):
    arr[i] = i + 1  # Exemplo: preenchendo com valores de 1 a 10

# Calcular o desvio padrão
std_dev = np.std(arr)
print(std_dev)



2.8722813232690143


In [27]:
## EX 2 - Juliana está corrigindo provas de seus alunos e para isso salva as notas em uma lista.
# Além de calcular a média da turma, Juliana também precisa determinar de forma rápida quem está acima e abaixo da média do colégio, e, para fazer isso de forma rápida, decidiu criar um array para auxiliá-la.
# A partir da lista de notas, como Juliana pode criar esse array?
# A) Utilizando o comando np.array(lista) --> (CORRETA)
# B) Utilizando a função np.to_array(lista)
# C) Utilizando a função Array(lista)
# D) Utilizando a função np.list_to_array(lista)

# Suponha que `notas` seja a lista de notas dos alunos
notas = [7.5, 8.0, 6.5, 9.0, 5.5, 8.5, 7.0, 6.0]

# Convertendo a lista em um array numpy
notas_array = np.array(notas)

# Calculando a média das notas
media_turma = np.mean(notas_array)
print("Média da turma:", media_turma)

# Determinando quem está acima e abaixo da média do colégio (por exemplo, média do colégio é 7.0)
media_colegio = 7.0
acima_da_media = notas_array[notas_array > media_colegio]
abaixo_da_media = notas_array[notas_array < media_colegio]

print("Notas acima da média do colégio:", acima_da_media)
print("Notas abaixo da média do colégio:", abaixo_da_media)



Média da turma: 7.25
Notas acima da média do colégio: [7.5 8.  9.  8.5]
Notas abaixo da média do colégio: [6.5 5.5 6. ]


### MASCARAS BOOLEANAS

In [12]:
is_covid_positive = np.array(['Yes', 'No', 'No', 'Yes', 'Yes', 'No'])

In [13]:
mask = (is_covid_positive == 'Yes')

In [14]:
print(is_covid_positive[mask])

['Yes' 'Yes' 'Yes']


In [15]:
is_covid_positive[mask] = 'C19'

In [16]:
print(is_covid_positive)

['C19' 'No' 'No' 'C19' 'C19' 'No']


In [17]:
notas = np.array([4.9, 6.5, 3.2, 6.7])

In [18]:
mask_notas = notas >= 5

In [19]:
print(mask_notas)

[False  True False  True]


### EXERCICIOS DE FIXAÇÃO II

In [ ]:
## EX 3 - Um estagiário está começando a trabalhar com Numpy. No meio dos tutoriais encontra menções a algo chamado máscara booleana.
# O conceito não ficou muito claro para ele, e ele pede a sua ajuda para explicar o que é esse recurso no numpy.
# Assinale a alternativa que explica o que é uma máscara booleana:

#a) É uma maneira de indexar objetos no numpy, que funciona de maneira similar a um dicionário
#b) É uma maneira de indexar objetos no numpy, que funciona de maneira similar a um filtro, que pode ser simples ou composto --> (CORRETA)
#c) É uma maneira de indexar objetos no numpy, que funciona de maneira similar a um filtro, a filtragem deve ser simples
#d) É uma ferramenta do numpy para disfarçar variáveis False e fingir que são True, apenas por um periodo no código


In [3]:
## EX 4 - Em uma escola, a média para aprovação é 7. As notas dos alunos estão armazenadas em um array chamado 'notas'.
#Escolha a expressão que pega 'notas' e salva em 'aprovados' um outro array booleano, com valor true apenas para as pessoas que passaram de ano:

#a) aprovados = notas >= 7 --> (CORRETA)
#b) aprovados = notas > 7
#c) aprovados <- notas >= 7
#d) aprovados = notas[notas >= 7]

# Array de notas dos alunos
notas = np.array([6.5, 7.0, 8.5, 5.0, 9.0, 7.5])

# Criando um array booleano indicando quem passou (nota >= 7)
aprovados = notas >= 7

print("Notas:", notas)
print("Aprovados:", aprovados)

Notas: [6.5 7.  8.5 5.  9.  7.5]
Aprovados: [False  True  True False  True  True]


### PANDAS SERIES

In [126]:
import pandas as pd

In [128]:
lista = [12, 23, 34, 45, 56, 67]

serie_pandas = pd.Series(lista)

In [130]:
print(serie_pandas)

0    12
1    23
2    34
3    45
4    56
5    67
dtype: int64


In [132]:
print(serie_pandas[0])

12


In [134]:
notas = {'Thiago' : 8, 'Guilherme' : 9.5, 'Juca' : 6.2}

In [136]:
serie_notas = pd.Series(notas)

In [138]:
print(serie_notas)

Thiago       8.0
Guilherme    9.5
Juca         6.2
dtype: float64


In [140]:
print(serie_notas['Thiago'])

8.0


In [142]:
print(serie_notas.describe())

count    3.000000
mean     7.900000
std      1.652271
min      6.200000
25%      7.100000
50%      8.000000
75%      8.750000
max      9.500000
dtype: float64


### EXERCICIO DE FIXAÇÃO III

In [ ]:
#EX 5 - Você deseja fazer cálculos sobre o campeonato brasileiro.
#A ideia é fazer alguns cálculos numéricos sobre gols feitos no campeonato brasileiro, como saber o total de gols.
#Para fazer essa soma com uma série do pandas, você deve:

#a) Usar o comando sum do numpy
#b) Usar o comando sum, que é um método das séries --> (CORRETA)
#c) Usar o comando sum, que é uma função do pandas
#d) Implementar um método que faça a soma de uma lista e utilizá-lo com a série


#EX 6 - Um professor está corrigindo a prova de seus alunos e precisa armazenar os valores e nomes em uma série.
#Escolha abaixo uma das vantagens de criar essa série a partir de um dicionário com os nomes dos alunos e suas respectivas notas:

#a) Otimização no processamento
#b) Fácil interpretabilidade --> (CORRETA)
#c) Possibilidade de filtrar elementos que ficaram acima de uma certa nota
#d) Possibilidade de encontrar um valor específico

### PANDAS DATAFRAMES

In [55]:
import pandas as pd

In [93]:
# Cria um dicionario com autores, preços e titulos

dictionary = {'Autores': ['Rick Riordan', 'J. R. R. Tolkien', 'Rick Riordan', 'Machado de Assis'],
              'Titulos': ['O ladrão de Raios', 'A Sociedade do Anel', 'Mar de Monstros', 'Memórias Postumas'],
              'Preços': [41.2, 35.7, 39.5, 40.5]}

In [95]:
## DataFrame

df = pd.DataFrame(dictionary)

In [97]:
df

Autores              Titulos  Preços
0      Rick Riordan    O ladrão de Raios    41.2
1  J. R. R. Tolkien  A Sociedade do Anel    35.7
2      Rick Riordan      Mar de Monstros    39.5
3  Machado de Assis    Memórias Postumas    40.5

In [99]:
df['Autores'][1]

'J. R. R. Tolkien'

In [101]:
df['Preços'].mean()

39.225

In [103]:
mascara = (df['Autores'] == 'Rick Riordan')

In [105]:
df[mascara]

Autores            Titulos  Preços
0  Rick Riordan  O ladrão de Raios    41.2
2  Rick Riordan    Mar de Monstros    39.5

In [107]:
# New row to be added
new_row = pd.DataFrame({'Autores' : ['Rick Riordan'], 'Titulos' : ['A Maldiçã do Titã'], 'Preços' : [40.20]})

# Concatenate the new row to the DataFrame
df = pd.concat([df, new_row], ignore_index=True)

In [109]:
df

Autores              Titulos  Preços
0      Rick Riordan    O ladrão de Raios    41.2
1  J. R. R. Tolkien  A Sociedade do Anel    35.7
2      Rick Riordan      Mar de Monstros    39.5
3  Machado de Assis    Memórias Postumas    40.5
4      Rick Riordan    A Maldiçã do Titã    40.2

In [111]:
mascara_correcao = df['Titulos'] == 'A Maldiçã do Titã'

In [113]:
df.loc[mascara_correcao, 'Titulos'] = 'A Maldição do Titã'

In [115]:
df

Autores              Titulos  Preços
0      Rick Riordan    O ladrão de Raios    41.2
1  J. R. R. Tolkien  A Sociedade do Anel    35.7
2      Rick Riordan      Mar de Monstros    39.5
3  Machado de Assis    Memórias Postumas    40.5
4      Rick Riordan   A Maldição do Titã    40.2

### EXERCICIO DE FIXAÇÃO IV

In [ ]:
#EX 7 - A lista da Billboard Hot 100 traz as 100 músicas mais populares da semana, com nome da música, artista, posição na última semana, posição na semana atual e semanas consecutivas na lista.
#Você extraiu esses dados para o dataframe 'billboard_100', que contem as colunas 'artista' e 'musica', e diversos outros dados que você deseja análisar. Como pode fazer para visualizar os nomes das músicas da Taylor Swift contidas na Billboard Hot 100 da semana? (apenas os nomes)

#a) billboard_100['artista'] == 'Taylor Swift'
#b) billboard_100[billboard_100['artista'] == 'Taylor Swift']
#c) billboard_100[billboard_100['artista'] == 'Taylor Swift']['musica'] --> (CORRETA)
#d) billboard_100[billboard_100['artista'].like('Taylor Swift')]['musica']

#EX 8 - Roberto trabalha com controle de estoque de uma loja de roupas e precisa fazer registros diários no dataframe de produtos, constando código, nome do produto, quantidade em estoque, tamanho e preço.
#Um dia, chegaram 5 unidades de 'camiseta azul de algodão', tamanho M, vendida por R$60,00 e com código 11.
#Porém, esse produto ainda não constava no inventário de estoque. Como Roberto pode adicioná-lo ao dataframe de dados?

#a) Com o comando produtos.append(11, camiseta azul de algodão, 5, M, 60.00)
#b) Com o comando produtos.append(camiseta azul de algodão)
#c) Com o comando produtos.add(11, 'camiseta azul de algodão', 5, 'M', 60.00) --> (CORRETA)
#d) Com o comando produtos.append(11, 'camiseta azul de algodão', 5, 'M', 60.00)

### ANALISANDO DADOS

In [146]:
import pandas as pd

In [152]:
taxis = pd.read_csv('taxis.csv')

In [154]:
taxis.head()

pickup              dropoff  passengers  distance  fare   tip  \
0  2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0  2.15   
1  2019-03-04 16:11:55  2019-03-04 16:19:00           1      0.79   5.0  0.00   
2  2019-03-27 17:53:01  2019-03-27 18:00:25           1      1.37   7.5  2.36   
3  2019-03-10 01:23:59  2019-03-10 01:49:51           1      7.70  27.0  6.15   
4  2019-03-30 13:27:42  2019-03-30 13:37:14           3      2.16   9.0  1.10   

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West   
1    0.0   9.30  yellow         cash  Upper West Side South   
2    0.0  14.16  yellow  credit card          Alphabet City   
3    0.0  36.95  yellow  credit card              Hudson Sq   
4    0.0  13.40  yellow  credit card           Midtown East   

            dropoff_zone pickup_borough dropoff_borough  
0    UN/Turtle Bay South      Manhattan       Manhattan  
1  Upper West Side South      Manhattan       Manhattan  
2           West Village      Manhattan       Manhattan  
3         Yorkville West      Manhattan       Manhattan  
4         Yorkville West      Manhattan       Manhattan

In [160]:
taxis['dropoff_borough'].value_counts()

dropoff_borough
Manhattan        5206
Queens            542
Brooklyn          501
Bronx             137
Staten Island       2
Name: count, dtype: int64

In [164]:
## Vizinhanças em que as casas costumam ser mais caras, oferecem melhores gorgetas

taxis.groupby(['dropoff_borough'])['tip'].agg(['mean', 'median'])

mean  median
dropoff_borough                   
Bronx             0.530803   0.000
Brooklyn          1.906248   0.000
Manhattan         1.954606   1.860
Queens            2.386273   0.000
Staten Island    14.165000  14.165

In [ ]:
#EX 9 - Cristina realizou ensaios mecânicos de um material e a máquina exportou os dados em um arquivo .csv.
#Como Cristina pode importar esses dados para acessá-los no pandas, da maneira mais prática possível, entre as opções abaixo?

#a) Utilizando o método pd.read_csv('nome_do_arquivo.csv') --> (CORRETA)
#b) Utilizando o metodo pd.read_file('nome_do_arquivo.csv)
#c) Utilizando o método read_data('nome_do_arquivo.csv')
#d) Utilizando o método nativo do python open, e fazendo em seguida o parseamento do arquivo

#EX 10 - Lúcia monitorou as temperaturas máximas de cada dia, durante todas as estações do ano de 2020 e armazenou os valores no DataFrame 'temperaturas'.
#Para um relatório, ela precisa saber a temperatura máxima média de cada estação. Como Lúcia pode calcular?

#a) temperaturas['temperatura'].agg('estacao').max()
#b) temperaturas.groupby('estacao')['temperatura'].max() --> (CORRETA)
#c) temperaturas.groupby(estacao)['temperatura'].max()
#d) temperaturas.agg('estacao')['temperatura'].max()

### TRATANDO DADOS

In [167]:
import pandas as pd

In [169]:
!pip install openpyxl

In [ ]:
auxiliar = df.loc[10031]

In [ ]:
auxiliar

In [ ]:
def limpa_preco(linha):
    linha['price'] = linha['price'].replace('R$', '')
    linha['price'] = linha['price'].replace('\n', '')
    linha['price'] = linha['price'].replace('/Mês', '')
    linha['price'] = linha['price'].replace('              ', '')
    return linha

In [ ]:
df.apply(lambda x: limpa_preco(x), axis=1)

In [ ]:
def ajusta_alugueis(linha):
    linha['price'] = linha['price'].replace('.', '')
    preco = int(linha['price'])
    if(preco < 10000):
        preco = preco * 200
    linha['price'] = preco
    return linha

In [ ]:
ajusta_alugueis(auxiliar)

In [ ]:
df.apply(lambda x: ajusta_alugueis(x), axis=1)